import type { LineStyle } from '@/types';

// Box-drawing character styles
export const LINE_STYLES: LineStyle[] = [
  {
    name: 'Light',
    horizontal: '─',
    vertical: '│',
    topLeft: '┌',
    topRight: '┐',
    bottomLeft: '└',
    bottomRight: '┘',
    topIntersect: '┬',
    bottomIntersect: '┴',
    leftIntersect: '├',
    rightIntersect: '┤',
    cross: '┼',
    upArrow: '↑',
    downArrow: '↓',
    leftArrow: '←',
    rightArrow: '→',
  },
  {
    name: 'Heavy',
    horizontal: '━',
    vertical: '┃',
    topLeft: '┏',
    topRight: '┓',
    bottomLeft: '┗',
    bottomRight: '┛',
    topIntersect: '┳',
    bottomIntersect: '┻',
    leftIntersect: '┣',
    rightIntersect: '┫',
    cross: '╋',
    upArrow: '▲',
    downArrow: '▼',
    leftArrow: '◄',
    rightArrow: '►',
  },
  {
    name: 'Double',
    horizontal: '═',
    vertical: '║',
    topLeft: '╔',
    topRight: '╗',
    bottomLeft: '╚',
    bottomRight: '╝',
    topIntersect: '╦',
    bottomIntersect: '╩',
    leftIntersect: '╠',
    rightIntersect: '╣',
    cross: '╬',
    upArrow: '⇑',
    downArrow: '⇓',
    leftArrow: '⇐',
    rightArrow: '⇒',
  },
  {
    name: 'Rounded',
    horizontal: '─',
    vertical: '│',
    topLeft: '╭',
    topRight: '╮',
    bottomLeft: '╰',
    bottomRight: '╯',
    topIntersect: '┬',
    bottomIntersect: '┴',
    leftIntersect: '├',
    rightIntersect: '┤',
    cross: '┼',
    upArrow: '↑',
    downArrow: '↓',
    leftArrow: '←',
    rightArrow: '→',
  },
  {
    name: 'ASCII',
    horizontal: '-',
    vertical: '|',
    topLeft: '+',
    topRight: '+',
    bottomLeft: '+',
    bottomRight: '+',
    topIntersect: '+',
    bottomIntersect: '+',
    leftIntersect: '+',
    rightIntersect: '+',
    cross: '+',
    upArrow: '^',
    downArrow: 'v',
    leftArrow: '<',
    rightArrow: '>',
  },
  {
    name: 'Dashed',
    horizontal: '┄',
    vertical: '┆',
    topLeft: '┌',
    topRight: '┐',
    bottomLeft: '└',
    bottomRight: '┘',
    topIntersect: '┬',
    bottomIntersect: '┴',
    leftIntersect: '├',
    rightIntersect: '┤',
    cross: '┼',
    upArrow: '↑',
    downArrow: '↓',
    leftArrow: '←',
    rightArrow: '→',
  },
];
